#!/usr/bin/env bash

HAS_PHP_CS_FIXER=false

PHP_CS_FIXER="vendor/bin/php-cs-fixer"

if [ ! -x "$PHP_CS_FIXER" ]; then
    PHP_CS_FIXER=$(which php-cs-fixer);
fi

if [ -x "$PHP_CS_FIXER" ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    git status --porcelain | grep -e '^[ACM]\(.*\).php$' | cut -c 3- | while read line; do
        "$PHP_CS_FIXER" fix --config=.php_cs "$line";
        git add "$line"
    done
    git status --porcelain | grep -e '^[R]\(.*\).php$' | cut -c 3- | while read line; do
        files=(${line// -> / })
        "$PHP_CS_FIXER" fix --config=.php_cs "${files[1]}";
        git add "${files[1]}"
    done
else
    echo ""
    echo "Please install php-cs-fixer, e.g.:"
    echo ""
    echo "  composer require --dev friendsofphp/php-cs-fixer"
    echo ""
fi